version: "3"

volumes:
  data:

services:
  db:
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hoodrobin
    volumes:
      - data:/var/lib/postgresql/data
